﻿using System;
using SME;

namespace ScalDecoder 
{

	[TopLevelInputBus] public interface Input0 : IBus { bool Bit { get; set; } }
	[TopLevelInputBus] public interface Input1 : IBus { bool Bit { get; set; } }
	[TopLevelInputBus] public interface Input2 : IBus { bool Bit { get; set; } }
	[TopLevelInputBus] public interface Input3 : IBus { bool Bit { get; set; } }
	[TopLevelInputBus] public interface Input4 : IBus { bool Bit { get; set; } }
	[TopLevelInputBus] public interface Input5 : IBus { bool Bit { get; set; } }
	[TopLevelInputBus] public interface Input6 : IBus { bool Bit { get; set; } }
	[TopLevelInputBus] public interface Input7 : IBus { bool Bit { get; set; } }

	[TopLevelOutputBus] public interface Output0 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output1 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output2 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output3 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output4 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output5 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output6 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output7 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output8 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output9 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output10 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output11 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output12 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output13 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output14 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output15 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output16 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output17 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output18 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output19 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output20 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output21 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output22 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output23 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output24 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output25 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output26 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output27 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output28 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output29 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output30 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output31 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output32 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output33 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output34 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output35 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output36 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output37 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output38 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output39 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output40 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output41 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output42 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output43 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output44 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output45 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output46 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output47 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output48 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output49 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output50 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output51 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output52 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output53 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output54 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output55 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output56 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output57 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output58 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output59 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output60 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output61 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output62 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output63 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output64 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output65 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output66 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output67 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output68 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output69 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output70 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output71 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output72 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output73 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output74 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output75 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output76 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output77 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output78 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output79 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output80 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output81 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output82 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output83 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output84 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output85 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output86 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output87 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output88 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output89 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output90 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output91 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output92 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output93 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output94 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output95 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output96 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output97 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output98 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output99 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output100 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output101 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output102 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output103 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output104 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output105 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output106 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output107 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output108 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output109 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output110 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output111 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output112 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output113 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output114 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output115 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output116 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output117 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output118 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output119 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output120 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output121 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output122 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output123 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output124 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output125 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output126 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output127 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output128 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output129 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output130 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output131 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output132 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output133 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output134 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output135 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output136 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output137 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output138 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output139 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output140 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output141 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output142 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output143 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output144 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output145 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output146 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output147 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output148 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output149 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output150 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output151 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output152 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output153 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output154 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output155 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output156 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output157 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output158 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output159 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output160 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output161 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output162 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output163 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output164 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output165 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output166 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output167 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output168 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output169 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output170 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output171 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output172 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output173 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output174 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output175 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output176 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output177 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output178 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output179 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output180 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output181 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output182 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output183 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output184 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output185 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output186 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output187 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output188 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output189 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output190 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output191 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output192 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output193 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output194 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output195 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output196 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output197 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output198 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output199 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output200 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output201 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output202 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output203 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output204 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output205 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output206 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output207 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output208 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output209 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output210 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output211 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output212 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output213 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output214 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output215 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output216 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output217 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output218 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output219 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output220 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output221 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output222 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output223 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output224 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output225 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output226 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output227 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output228 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output229 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output230 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output231 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output232 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output233 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output234 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output235 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output236 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output237 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output238 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output239 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output240 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output241 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output242 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output243 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output244 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output245 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output246 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output247 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output248 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output249 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output250 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output251 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output252 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output253 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output254 : IBus { bool Bit { get; set; } }
	[TopLevelOutputBus] public interface Output255 : IBus { bool Bit { get; set; } }

}
