﻿using System;
using SME;

[InitializedBus] public interface InputA0 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA1 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA2 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA3 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA4 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA5 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA6 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA7 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA8 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA9 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA10 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA11 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA12 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA13 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA14 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA15 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA16 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA17 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA18 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA19 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA20 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA21 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA22 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA23 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA24 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA25 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA26 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA27 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA28 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA29 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA30 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputA31 : IBus { int Bit { get; set; } }

[InitializedBus] public interface InputB0 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB1 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB2 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB3 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB4 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB5 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB6 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB7 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB8 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB9 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB10 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB11 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB12 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB13 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB14 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB15 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB16 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB17 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB18 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB19 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB20 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB21 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB22 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB23 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB24 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB25 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB26 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB27 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB28 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB29 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB30 : IBus { int Bit { get; set; } }
[InitializedBus] public interface InputB31 : IBus { int Bit { get; set; } }
