set_property PACKAGE_PIN U14 [get_ports Output_And]
set_property PACKAGE_PIN W22 [get_ports Output_Not]
set_property PACKAGE_PIN U19 [get_ports Output_Or]
set_property PACKAGE_PIN V22 [get_ports Output_Xor]
set_property PACKAGE_PIN M15 [get_ports Input_bit1]
set_property PACKAGE_PIN H17 [get_ports Input_bit2]
set_property PACKAGE_PIN P16 [get_ports RST]
set_property IOSTANDARD LVCMOS18 [get_ports Input_bit1]
set_property IOSTANDARD LVCMOS18 [get_ports CLK]
set_property IOSTANDARD LVCMOS18 [get_ports Input_bit2]
set_property IOSTANDARD LVCMOS18 [get_ports Output_And]
set_property IOSTANDARD LVCMOS18 [get_ports Output_Not]
set_property IOSTANDARD LVCMOS18 [get_ports Output_Or]
set_property IOSTANDARD LVCMOS18 [get_ports Output_Xor]
set_property IOSTANDARD LVCMOS18 [get_ports RST]

create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports CLK]
